apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: apis-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.59.138-192.168.59.138
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: apis-pool
  namespace: metallb-system
spec:
  ipAddressPools:
  - apis-pool
